# Réseau partagé entre Gateway et Keycloak
networks:
  skillshub-net:
    external: true

services:
  # Gateway Service
  gateway-service:
    build: .
    container_name: gateway-service
    #todo change it when changing environment
    env_file:
      - ./envs/dev/docker-hybrid.env
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "auth.skillshub.local:host-gateway"
    networks:
      - skillshub-net

